name: Create Cypress report
on:
  push:
    branches:
      - 'main'

jobs:

  cypress-e2e-chrome88:
    name: Run on Chrome 88
    runs-on: ubuntu-18.04
    container: cypress/browsers:node14.17.0-chrome88-ff89
    steps:
      - uses: actions/checkout@v2

      - name: Install a project with a clean slate
        run: |
          yarn ci
          $(yarn bin)/cypress cache path
          $(yarn bin)/cypress cache list
          $(yarn bin)/cypress verify

      - name: Run Cypress tests
        run: yarn start test:chrome
        continue-on-error: true

      - name: Copy test execution videos
        run: |
          mkdir public
          cp -r cypress/videos public/videos

      - name: Merge test results into one
        run: yarn start report:merge

      - name: Generate HTML report
        run: yarn start report:generate --template ./template.html  mv report.html public/index.html

      - name: Deploy report page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN  }}
          publish_dir: ./public
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@yunchaehyun.github.com'
